server:
  port: 18090
  servlet:
    session:
      timeout: 1h
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ## redirection http 현상 제거 ##
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: varchar
  mapper-locations: mappers/**/*.xml

logging:
  config: classpath:logback.xml
spring:
  application:
    name: NANURI IT Corp Risk Management System
  datasource:
    # driver-class-name: com.tmax.tibero.jdbc.TbDriver
    url: jdbc:log4jdbc:tibero:thin:@172.30.1.32:8629:tibero
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # url: jdbc:tibero:thin:@172.30.1.32:8629:tibero
    username: RAMS
    password: Nanuriwork1!
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    database-platform: com.tmax.tibero.hibernate.dialect.TiberoDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle9Dialect 
        # hbm2ddl.auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant-path-matcher

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      port: 35729
      
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: 2000MB
