# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
permissions:
  contents: read

jobs:

  ## 빌드
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Set up JDK 11
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '11'
    #     distribution: 'temurin'
    - name : granted execute to gradlew
      run : cd ~/rams2/rams2/rams2/rams2 | chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - name : Show structure of artifact files
      run:  ls -ahl ./build/libs/*.jar

    ## 서버에 빌드jar 전송
    - name: Transfer artifact
      uses: appleboy/scp-action@master
      with:
        username: ${{ secrets.SSH_USERNAME }}
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        rm: true
        source: "./build/libs/*.jar"
        target: ${{ secrets.SCP_RAMS_PATH }}
        ## 작업에 사용했던 디렉토리를 경로상에서 제거
        strip_components: 1
        
    ## 전송 파일 확인
    - name: Show structure of transfer files
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USERNAME }}
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ secrets.SCP_RAMS_PATH }}
          ls -alh ./libs

  ## 배포
  deploy :
    # runs-on : self-hosted
    runs-on: ubuntu-latest
    needs : build
    steps : 
      # - name : Depoly
        # run : cd ~/rams && RUNNER_TRACKING_ID="" && ./startRams.sh &
        # run : /home/nanuri/rams/startRams.sh &

      ## 실행 로그 확인
      - name: Run Project
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            ~/rams2/startRams.sh
